### ISSUE TITLE
sentinel fmt gives panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by sheeeng** [hashicorp/terraform-foundational-policies-library#31]
```text
Run sentinel fmt -check=true $(find . -name "*.sentinel")
panic: runtime error: index out of range [1] with length 1
```

See the complete [log](https://github.com/hashicorp/terraform-foundational-policies-library/pull/30/checks?check_run_id=1315266591).

See https://github.com/thrashr888/sentinel-simulator-docker/issues/2.

**Comment by thrashr888** [comment]
I've merged thrashr888/sentinel-simulator-docker#2. Thanks!
