### ISSUE TITLE
azure-cis-3.8-storage-trusted-microsoft-services-is-enabled bypass rule checking

### ISSUE THREAD

**Issue by glnarter** [hashicorp/terraform-foundational-policies-library#41]
I am new to Sentinel and taking advantage of these foundation policies to get started.

I came across what might be an issue with azure-cis-3.8-storage-trusted-microsoft-services-is-enabled.

https://github.com/hashicorp/terraform-foundational-policies-library/blob/8cbbc68aa90eeb9671e7be8cb8564e7fb4c3f070/cis/azure/storage/azure-cis-3.8-storage-trusted-microsoft-services-is-enabled/azure-cis-3.8-storage-trusted-microsoft-services-is-enabled.sentinel#L29

In testing this policy I kept getting failures on the "pass" test until I changed line 29 from "all" to "any". 
I believe this is because bypass rules in Azure may have more than one entry thus we want to return true if "any" of them are AzureServices.

Trying to find more documentation on the use of "all", any" and "for" I found this in the official documentation:
https://docs.hashicorp.com/sentinel/language/scope

It appears that the example code on that page was for another topic and thus does not illustrate how to use these scopes.

Thanks!

**Comment by hcrhall** [comment]
@glnarter I have raised https://github.com/hashicorp/terraform-foundational-policies-library/pull/42 to resolve this issue. Thanks for raising this issue 👍
